title: SergueiVM
owner: SergueiVM
description: >- # this means to ignore newlines until "baseurl:"
  ...me dedico a hacer software
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sergueivm.es" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assest/images/logo.png
google-analytics: UA-124836677-1
socials:
  twitter: SergueiVM
  github: sergueivm
  linkedin: sergueivicario

# Build settings
markdown: kramdown
show_drafts: false
future: false
timezone: Europe/Madrid
locale: es_ES
lang: es

permalink: /:categories/:title

sass:
  style: compact

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-target-blank
