title: SergueiVM
owner: SergueiVM
description: >- # this means to ignore newlines until "baseurl:"
  ...me dedico a hacer software
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
socials:
  twitter: SergueiVM
  github: sergueivm
  linkedin: sergueivicario

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
show_drafts: false
future: false
timezone: Europe/Madrid

plugins:
  - jekyll-feed